#names used for images loading in Display

class Rooms_db :
    rooms = {
        #yellow rooms
        'Bookshop':'yellow',
        'Casino':'yellow',
        'Commissary':'yellow',
        'GiftShop':'yellow',
        'Kitchen':'yellow',
        'LaundryRoom':'yellow',
        'Locksmith':'yellow',
        'Showroom':'yellow',
        'TheArmory':'yellow',
        'TradingPost':'yellow',

        #blue rooms
        'Antechamber':'blue',
        'Aquarium':'blue',
        'Attic':'blue',
        'Ballroom':'blue',
        'BilliardRoom':'blue',
        'BoilerRoom':'blue',
        'ChamberofMirrors':'blue',
        'Classroom':'blue',
        'ClockTower':'blue',
        'Closet':'blue',
        'CoatCheck':'blue',
        'ConferenceRoom':'blue',
        'Den':'blue',
        'DiningRoom':'blue',
        'Dovecote':'blue',
        'DraftingStudio':'blue',
        'DrawingRoom':'blue',
        'EntranceHall':'blue',
        'Freezer':'blue',
        'Gallery':'blue',
        'Garage':'blue',
        'Laboratory':'blue',
        'Library':'blue',
        'LockerRoom':'blue',
        'MailRoom':'blue',
        'Mechanarium':'blue',
        'MusicRoom':'blue',
        'Nook':'blue',
        'Observatory':'blue',
        'Office':'blue',
        'Pantry':'blue',
        'Parlor':'blue',
        'Planetarium':'blue',
        'PumpRoom':'blue',
        'Room46':'blue',
        'Room8':'blue',
        'Rotunda':'blue',
        'RumpusRoom':'blue',
        'Schoolhouse':'blue',
        'Security':'blue',
        'Shelter':'blue',
        'Shrine':'blue',
        'SpareRoom':'blue',
        'Storeroom':'blue',
        'Study':'blue',
        'TheKennel':'blue',
        'ThePool':'blue',
        'ThroneRoom':'blue',
        'Tomb':'blue',
        'Toolshed':'blue',
        'TreasureTrove':'blue',
        'TrophyRoom':'blue',
        'UtilityCloset':'blue',
        'Vault':'blue',
        'WalkinCloset':'blue',
        'WineCellar':'blue',
        'Workshop':'blue',

        #orange rooms
        'Corridor':'orange',
        'EastWingHall':'orange',
        'Foyer':'orange',
        'GreatHall':'orange',
        'Hallway':'orange',
        'Passageway':'orange',
        'SecretPassage':'orange',
        'Tunnel':'orange',
        'Vestibule':'orange',
        'WestWingHall':'orange',

        #violet rooms
        'Bedroom':'violet',
        'Boudoir':'violet',
        'BunkRoom':'violet',
        'Dormitory':'violet',
        'GuestBedroom':'violet',
        'HerLadyshipsChamber':'violet',
        'Hovel':'violet',
        'MasterBedroom':'violet',
        'Nursery':'violet',
        'ServantsQuarters':'violet',

        #green rooms
        'Cloister':'green',
        'Conservatory':'green',
        'Courtyard':'green',
        'Greenhouse':'green',
        'MorningRoom':'green',
        'Patio':'green',
        'RootCellar':'green',
        'SecretGarden':'green',
        'Solarium':'green',
        'Terrace':'green',
        'Veranda':'green',

        #red rooms
        'Archives':'red',
        'Chapel':'red',
        'ClosedExhibit':'red',
        'Darkroom':'red',
        'Furnace':'red',
        'Gymnasium':'red',
        'Lavatory':'red',
        'Lost&Found':'red',
        'MaidsChamber':'red',
        'WeightRoom':'red'
    }

